name: Deploy Oracle Database

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install Oracle
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
       
        echo "=== Install docker & docker-compose ==="
        sudo apt update -y
        
        if docker --version &> /dev/null
        then
          echo "Docker is already installed."
        else
          echo "Docker is not installed. Installing..."
          sudo apt update -y
          sudo apt install docker.io -y
        fi
        
        if docker-compose --version &> /dev/null
        then
          echo "Docker Compose is already installed."
        else
          echo "Docker Compose is not installed. Installing..."
          sudo apt install docker-compose -y
        fi
        
        echo "=== clone repo hr ==="
        if [ -d "db-sample-schemas" ]; then
          echo "=== Removing existing directory db-sample-schemas ==="
          rm -rf db-sample-schemas
        fi
        git clone https://github.com/oracle-samples/db-sample-schemas.git
        
        echo "=== docker pull ==="
        sudo docker pull container-registry.oracle.com/database/free:latest
        
        echo "=== Creating a volume ==="
        sudo docker volume create oracledb-volume
        
        echo "=== Configuring docker compose ==="
        mkdir -p oracle_database
        cd oracle_database
        sudo tee docker-compose.yml << 'EOL'
        # oracle database: container configuration
        services:
          oracle_database:
            image: container-registry.oracle.com/database/free:latest
            container_name: oracle_database
            env_file:
              - ./.env
            volumes:
              - oracledb-volume:/opt/oracle/oradata:rw
            hostname: oracledbhost
            restart: always
            init: true
            tty: true
            ports:
              - 1521:1521
        volumes:
          oracledb-volume:
            external: true
        EOL

        echo "=== Setting up environment variables ==="
        sudo tee ./.env << 'EOFS'
        # environment variables
        ORACLE_PWD=${{ secrets.ORACLE_PWD }}
        COMPOSE_HTTP_TIMEOUT=600
        EOFS

        echo "=== Starting up the database ==="
        # export DOCKER_CLIENT_TIMEOUT=120
        sudo docker-compose -v up -d

        echo "=== Waiting for database to be ready ==="
        sleep 5 # Даем время контейнеру запуститься
        sudo docker-compose ps --services --filter "status=running"
        
        echo "=== Copying *.sql to container ==="
        sudo docker cp ~/db-sample-schemas/human_resources/ oracle_database:/tmp
        EOF
