name: Deploy Oracle Database

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install Oracle
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        echo "=== clone repo hr ==="
        git clone https://github.com/oracle-samples/db-sample-schemas.git
        
        echo "=== docker pull ==="
        sudo docker pull container-registry.oracle.com/database/free:latest
        
        echo "=== Creating a volume ==="
        sudo docker volume create oracledb-volume
        
        echo "=== Configuring docker compose ==="
        mkdir -p oracle_database
        cd oracle_database
        sudo tee docker-compose.yml << 'EOL'
        # oracle database: container configuration
        services:
          oracle_database:
            environment:
              - HR_PASSWORD=${{ secrets.ORACLE_PWD }}
            image: container-registry.oracle.com/database/free:latest
            container_name: oracle_database
            env_file:
              - ./.env
            volumes:
              - oracledb-volume:/opt/oracle/oradata:rw
            hostname: oracledbhost
            restart: always
            init: true
            tty: true
            ports:
              - 1521:1521
        volumes:
          oracledb-volume:
            external: true
        EOL

        echo "=== Setting up environment variables ==="
        sudo tee ./.env << 'EOFS'
        # environment variables (without spaces)
        ORACLE_PWD=${{ secrets.ORACLE_PWD }}
        EOFS

        echo "=== Starting up the database ==="
        sudo docker compose up -d

        echo "=== Waiting for database to be ready ==="
        sleep 10 # Даем время контейнеру запуститься
        echo | sudo docker ps
        
        echo "=== Copying *.sql to container ==="
        sudo docker cp ~/db-sample-schemas/human_resources/ oracle_database:/tmp

        echo "=== Install HR database ==="
        sudo docker exec -i oracle_database sqlplus -S "sys/${{ secrets.ORACLE_PWD }}@//localhost:1521/FREEPDB1 as sysdba" <<EOC
        @/tmp/human_resources/hr_install.sql
        $HR_PASSWORD
        USERS
        YES
        EOC
        EOF
